# Generated by Django 6.0.7 on 2026-07-13 12:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='receipts/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('merchant', models.CharField(blank=True, max_length=150)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('items', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_scans', to='ledger.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipt_scans',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='receipt_sca_user_id_402348_idx'), models.Index(fields=['user', 'status'], name='receipt_sca_user_id_26c616_idx'), models.Index(fields=['transaction'], name='receipt_sca_transac_2e3596_idx')],
            },
        ),
    ]
