# Generated by Django 6.0.7 on 2026-07-13 12:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Discussion', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('SPENDING_PATTERN', 'Spending Pattern'), ('BUDGET_ALERT', 'Budget Alert'), ('SAVINGS_OPPORTUNITY', 'Savings Opportunity'), ('SUBSCRIPTION_DETECTED', 'Subscription Detected'), ('DUPLICATE_CHARGE', 'Duplicate Charge'), ('BILL_REMINDER', 'Bill Reminder'), ('FINANCIAL_HEALTH', 'Financial Health'), ('GOAL_PROGRESS', 'Goal Progress')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate when clicked', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'AI Model')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(help_text='API endpoint called', max_length=100)),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens consumed')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
