# Generated by Django 6.0.7 on 2026-07-13 12:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('BILL', 'Bill'), ('SALARY', 'Salary'), ('GOAL', 'Goal'), ('SUBSCRIPTION', 'Subscription'), ('OTHER', 'Other')], max_length=20)),
                ('event_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('is_reminder_enabled', models.BooleanField(default=True)),
                ('reminder_days', models.IntegerField(default=3)),
                ('is_recurring', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='bills.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_calendar_events',
                'ordering': ['event_date', 'title'],
                'indexes': [models.Index(fields=['user', 'event_date'], name='financial_c_user_id_4639f6_idx'), models.Index(fields=['user', 'event_type'], name='financial_c_user_id_8b7ee0_idx'), models.Index(fields=['user', 'is_reminder_enabled'], name='financial_c_user_id_e8fbaa_idx')],
            },
        ),
    ]
